name: 7.3 cli

on:
  push:
    branches:
      - 'master'

env:
  VERSION: '7.3'
  MODE: cli

jobs:
  cli:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.VERSION }}/${{ env.MODE }}/
          push: true
          tags: |
            tuzex/php:${{ env.VERSION }}-${{ env.MODE }}
            ghcr.io/tuzex/php:${{ env.VERSION }}-${{ env.MODE }}
          target: ${{ env.ENVIRONMENT }}

  cli--dev:
    runs-on: ubuntu-latest
    env:
      FLAG: --dev
      ENVIRONMENT: dev
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.VERSION }}/${{ env.MODE }}/
          push: true
          tags: |
            tuzex/php:${{ env.VERSION }}-${{ env.MODE }}${{ env.FLAG }}
            ghcr.io/tuzex/php:${{ env.VERSION }}-${{ env.MODE }}${{ env.FLAG }}
          target: ${{ env.ENVIRONMENT }}

